version: '3'

services:
    mysql:
        image: mysql
        restart: always
        volumes:                            # 今回追加
            - ./mysql:/var/lib/mysql        # ホスト側の ./mysql をコンテナ内の /var/lib/mysql にマウント
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        ports:
            - "3306:3306"
    wordpress:
        depends_on:
            - mysql
        build:
            context: ./docker
        container_name: wordpress
        volumes:                            # 今回追加
            - ./wordpress:/var/www/html     # ホスト側の ./wordpress をコンテナ内の /var/www/html にマウント
            - ./conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "8080:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        user: "${UID_GID}"